# Generated by Django 4.1.5 on 2023-01-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_a2c5ee_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_a2c5ee_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
