# Generated by Django 4.1.5 on 2023-01-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_store_custo_last_na_a2c5ee_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='titel',
            new_name='title',
        ),
    ]
